Repository googleapis/java-deploy, pull requests merged in 2022-01, with the labels that each got.

#57 chore: change name to api_shortname in .repo-metadata.json
  .repo-metadata.json
Labels: automerge, api: clouddeploy, owlbot:ignore

#61 chore: update release-level in .repo-metadata.json
  .repo-metadata.json
Labels: automerge, api: clouddeploy, owlbot:ignore

#63 feat: promote to GA
  .repo-metadata.json
  README.md
Labels: automerge, api: clouddeploy

#65 chore: add codeowners
  .github/CODEOWNERS
  .repo-metadata.json
Labels: api: clouddeploy
